/**:
  ros__parameters:
    robot_description_kinematics:
      ur_manipulator:
        kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
        solve_type: Distance # Speed, Manipulation1, Manipulation2, Distance
        kinematics_solver_timeout: 0.05 # 0.005
        kinematics_solver_attempts: 10
